const categories = [
  { id: "all", label: "All" },
  { id: "ceramics", label: "Ceramics" },
  { id: "painting", label: "Painting" },
  { id: "brocade", label: "Brocade" },
  { id: "bamboo", label: "Bamboo" },
  { id: "wood", label: "Wood" },
  { id: "incense", label: "Incense" },
  { id: "stone", label: "Fengshui Stone" },
  { id: "waterpuppet", label: "Water Puppets" },
];

const filters = [
  {
    title: "Price",
    open: true,
    options: [
      "Under $25",
      "$25 – $50",
      "$50 – $100",
      "$100 & over",
    ],
  },
  {
    title: "Craft Village",
    open: false,
    options: [
      "Bát Tràng · Hanoi",
      "Vạn Phúc · Hà Đông",
      "Hạ Thái · Hà Nội",
      "Phú Vinh · Hà Nội",
      "Đồng Kỵ · Bắc Ninh",
      "Non Nước · Đà Nẵng",
    ],
  },
  {
    title: "Material",
    open: false,
    options: [
      "Ceramic",
      "Silk",
      "Lacquer",
      "Bamboo & Rattan",
      "Wood",
      "Sandalwood",
    ],
  },
  {
    title: "Availability",
    open: false,
    options: ["In stock", "Low stock"],
  },
  {
    title: "Rating",
    open: false,
    options: ["★★★★ & up", "★★★★★ only"],
  },
];

const sortOptions = [
  {
    id: "featured",
    label: "Best Sellers",
  },
  {
    id: "low",
    label: "Price: Low to high",
  },
  {
    id: "high",
    label: "Price: High to low",
  },
  {
    id: "name",
    label: "Name: A–Z",
  },
];

const products = [
  {
    id: 1,
    category: "ceramics",
    maker: "Bát Tràng",
    name: "Sculpted Face Ceramic Mug",
    price: "$68.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 48,
    tag: "Bestseller",
    variant: "1 Size",
    image: "/images/shopping_items/ceramic/ceramic1.png",
    alt: "Cream ceramic mug sculpted with a face and pink bow",
    reviewNumber: 1,
  },
  {
    id: 2,
    category: "ceramics",
    maker: "Bát Tràng",
    name: "Hand-Painted Ribbon Ceramic Mug Set",
    price: "$54.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 63,
    tag: "",
    variant: "Set of 8",
    image: "/images/shopping_items/ceramic/ceramic2.png",
    alt: "Set of hand-painted ceramic mugs decorated with ribbons, flowers, hearts and cherries",
    reviewNumber: 2,
  },
  {
    id: 3,
    category: "brocade",
    maker: "Vạn Phúc",
    name: "Brocade Blanket",
    price: "$56.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 31,
    tag: "New",
    variant: "Set of 4",
    image: "/images/shopping_items/brocade/brocade1.png",
    alt: "Stack of four folded traditional brocade blankets",
    reviewNumber: 3,
  },
  {
    id: 4,
    category: "brocade",
    maker: "Vạn Phúc",
    name: "Handmade Brocade Horse Figurine",
    price: "$45.00",
    oldPrice: "$52.00",
    rating: "★★★★★",
    reviewCount: 87,
    tag: "Sale",
    variant: "1 Size",
    image: "/images/shopping_items/brocade/brocade2.png",
    alt: "Colourful handmade horse figurine covered in traditional brocade patterns",
    reviewNumber: 4,
  },
  {
    id: 5,
    category: "incense",
    maker: "Quảng Phú Cầu",
    name: "Hand-Rolled Cinnamon Incense Bundle",
    price: "$34.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 12,
    tag: "",
    variant: "Set of 3 Bundles",
    image: "/images/shopping_items/incense/incense1.png",
    alt: "Three bundles of hand-rolled cinnamon incense sticks",
    reviewNumber: 5,
  },
  {
    id: 6,
    category: "incense",
    maker: "Quảng Phú Cầu",
    name: "Natural Incense Cone Gift Set",
    price: "$38.00",
    oldPrice: "",
    rating: "★★★★☆",
    reviewCount: 24,
    tag: "",
    variant: "24 Cones",
    image: "/images/shopping_items/incense/incense2.png",
    alt: "Natural brown incense cones in a metal gift tin",
    reviewNumber: 6,
  },
  {
    id: 7,
    category: "painting",
    maker: "Đông Hồ",
    name: "Vietnamese Folk Painting — Child with Carp",
    price: "$120.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 19,
    tag: "Only 3 left",
    variant: "1 Framed Print",
    image: "/images/shopping_items/painting/painting_1.png",
    alt: "Framed Vietnamese folk painting of a child holding a large carp",
    reviewNumber: 7,
  },
  {
    id: 8,
    category: "painting",
    maker: "Đông Hồ",
    name: "Vietnamese Mother and Child Painting",
    price: "$16.00",
    oldPrice: "",
    rating: "★★★★☆",
    reviewCount: 19,
    tag: "",
    variant: "1 Framed Print",
    image: "/images/shopping_items/painting/painting_2.png",
    alt: "Framed Vietnamese painting of a mother holding her child",
    reviewNumber: 8,
  },
  {
    id: 9,
    category: "stone",
    maker: "Non Nước",
    name: "Natural Stone Feng Shui Sculpture",
    price: "$46.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 27,
    tag: "New",
    variant: "1 Piece",
    image: "/images/shopping_items/stone/stone1.png",
    alt: "Polished natural stone feng shui sculpture",
    reviewNumber: 9,
  },
  {
    id: 10,
    category: "stone",
    maker: "Non Nước",
    name: "Jade Lotus Mirror Sculpture",
    price: "$32.00",
    oldPrice: "",
    rating: "★★★★☆",
    reviewCount: 15,
    tag: "",
    variant: "1 Piece",
    image: "/images/shopping_items/stone/stone2.png",
    alt: "Jade-coloured lotus and mirror sculpture",
    reviewNumber: 10,
  },
  {
    id: 11,
    category: "waterpuppet",
    maker: "Đào Thục",
    name: "Traditional Water Puppet — Royal Lady",
    price: "$72.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 22,
    tag: "",
    variant: "1 Puppet",
    image: "/images/shopping_items/waterpuppet/water1.png",
    alt: "Traditional Vietnamese water puppet depicting a royal lady",
    reviewNumber: 11,
  },
  {
    id: 12,
    category: "waterpuppet",
    maker: "Đào Thục",
    name: "Traditional Water Puppet — Drum Performer",
    price: "$89.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 9,
    tag: "New",
    variant: "1 Puppet",
    image: "/images/shopping_items/waterpuppet/water2.png",
    alt: "Traditional Vietnamese water puppet carrying a drum",
    reviewNumber: 12,
  },
  {
    id: 13,
    category: "wood",
    maker: "Đồng Kỵ",
    name: "Carved Wooden Longevity Deity Statue",
    price: "$29.00",
    oldPrice: "",
    rating: "★★★★☆",
    reviewCount: 14,
    tag: "New",
    variant: "1 Size",
    image: "/images/shopping_items/wood/wood1.png",
    alt: "Hand-carved wooden longevity deity statue",
    reviewNumber: 13,
  },
  {
    id: 14,
    category: "wood",
    maker: "Đồng Kỵ",
    name: "Hand-Carved Wooden Woman Sculpture",
    price: "$22.00",
    oldPrice: "",
    rating: "★★★★★",
    reviewCount: 33,
    tag: "",
    variant: "1 Size",
    image: "/images/shopping_items/wood/wood2.png",
    alt: "Abstract hand-carved wooden sculpture of a seated woman",
    reviewNumber: 14,
  },
  {
    id: 15,
    category: "wood",
    maker: "Đồng Kỵ",
    name: "Carved Mother and Child Figurine",
    price: "$27.00",
    oldPrice: "",
    rating: "★★★★☆",
    reviewCount: 11,
    tag: "New",
    variant: "1 Size",
    image: "/images/shopping_items/wood/wood3.png",
    alt: "Carved figurine of a smiling mother embracing her child",
    reviewNumber: 15,
  },
];

const categoryCounts = categories.reduce((counts, category) => {
  if (category.id === "all") {
    counts[category.id] = products.length;
  } else {
    counts[category.id] = products.filter(
      (product) => product.category === category.id
    ).length;
  }

  return counts;
}, {});

const getProductsPageData = () => ({
  pageTitle: "Shop All",
  categories,
  categoryCounts,
  filters,
  sortOptions,
  products,
});

module.exports = {
  getProductsPageData,
};